import type { Metadata } from "next";
import { Archivo, Geist, Geist_Mono, Open_Sans, Roboto } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/auth/auth-provider";
import Navbar from "@/components/Header/Navbar";
import { ScrollProgress } from "@/components/magicui/scroll-progress";
import SmoothScroll from "@/lib/SmoothScroll";
import Footer from "@/components/Others/Fotoer";

const geistSans = Archivo({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>   
      <body
        className={`${geistSans.className} antialiased`}
        >
          <SmoothScroll>
           <ScrollProgress className="top-0" />
           <Navbar/>
           {children}
           <Footer/>
          </SmoothScroll>
      </body>
        </AuthProvider>
    </html>
  );
}
